neo4j:
  name: neo4j-db
  resources:
    cpu: "0.5"
    memory: "2Gi"
  minimumClusterSize: 3

  # Uncomment to set the initial password
  password: "my-initial-password"

  # Uncomment to use enterprise edition
  edition: "enterprise"
  acceptLicenseAgreement: "yes"

volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 2Gi

env:
  NEO4J_PLUGINS: '["apoc"]'
